services:
  - type: web
    name: origami-api
    env: production
    plan: starter
    runtime: docker
    branch: main
    rootDir: .
    autoDeploy: true
    healthCheckPath: /swagger/index.html
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Swagger__Enabled
        value: "true"
      - key: ConnectionStrings__SQLServerDatabase
        sync: false # set this in Render dashboard; currently points to local SQL Server
      - key: Jwt__Issuer
        sync: false
      - key: Jwt__Audience
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Authentication__Google__ClientId
        sync: false
      - key: Authentication__Google__ClientSecret
        sync: false
      - key: Authentication__Google__CallbackPath
        value: /signin-google

